INSERT INTO public.products (title, slug, category_id)
VALUES 
  ('Amla / Indian Gooseberry', 'amla-indian-gooseberry', (SELECT id FROM public.categories WHERE name = 'Immunity & Vitality' LIMIT 1)),
  ('Andrographis / Kalmegh', 'andrographis-kalmegh', (SELECT id FROM public.categories WHERE name = 'Immunity & Vitality' LIMIT 1)),
  ('Ashwagandha 5% HPLC', 'ashwagandha-5-hplc', (SELECT id FROM public.categories WHERE name = 'Adaptogen & Stress Relief' LIMIT 1)),
  ('Bacopa / Brahmi', 'bacopa-brahmi', (SELECT id FROM public.categories WHERE name = 'Brain & Cognitive' LIMIT 1)),
  ('Berberine HCl 97%', 'berberine-hcl-97', (SELECT id FROM public.categories WHERE name = 'Blood Sugar & Metabolic' LIMIT 1)),
  ('Bhringraj Extract', 'bhringraj-extract', (SELECT id FROM public.categories WHERE name = 'Skin, Hair & Antimicrobial' LIMIT 1)),
  ('Black Seed / Kalonji', 'black-seed-kalonji', (SELECT id FROM public.categories WHERE name = 'Immunity & Vitality' LIMIT 1)),
  ('Boswellia', 'boswellia', (SELECT id FROM public.categories WHERE name = 'Anti-Inflammatory' LIMIT 1)),
  ('Coleus Forskohlii', 'coleus-forskohlii', (SELECT id FROM public.categories WHERE name = 'Blood Sugar & Metabolic' LIMIT 1)),
  ('Fenugreek / Methi', 'fenugreek-methi', (SELECT id FROM public.categories WHERE name = 'Blood Sugar & Metabolic' LIMIT 1)),
  ('Ginger Extract', 'ginger-extract', (SELECT id FROM public.categories WHERE name = 'Digestive & Gut Health' LIMIT 1)),
  ('Guduchi / Giloy', 'guduchi-giloy', (SELECT id FROM public.categories WHERE name = 'Immunity & Vitality' LIMIT 1)),
  ('Gymnema Sylvestre', 'gymnema-sylvestre', (SELECT id FROM public.categories WHERE name = 'Blood Sugar & Metabolic' LIMIT 1)),
  ('Hibiscus Extract', 'hibiscus-extract', (SELECT id FROM public.categories WHERE name = 'Skin, Hair & Antimicrobial' LIMIT 1)),
  ('Holy Basil / Tulsi Extract', 'holy-basil-tulsi-extract', (SELECT id FROM public.categories WHERE name = 'Adaptogen & Stress Relief' LIMIT 1)),
  ('Lion''s Mane Beta-Glucan', 'lions-mane-beta-glucan', (SELECT id FROM public.categories WHERE name = 'Brain & Cognitive' LIMIT 1)),
  ('Lion''s Mane Mushroom Extract', 'lions-mane-mushroom-extract', (SELECT id FROM public.categories WHERE name = 'Brain & Cognitive' LIMIT 1)),
  ('Moringa Extract', 'moringa-extract', (SELECT id FROM public.categories WHERE name = 'Immunity & Vitality' LIMIT 1)),
  ('Mucuna Pruriens', 'mucuna-pruriens', (SELECT id FROM public.categories WHERE name = 'Adaptogen & Stress Relief' LIMIT 1)),
  ('Neem', 'neem', (SELECT id FROM public.categories WHERE name = 'Skin, Hair & Antimicrobial' LIMIT 1)),
  ('Noni Extract', 'noni-extract', (SELECT id FROM public.categories WHERE name = 'Immunity & Vitality' LIMIT 1)),
  ('Piperine 95%', 'piperine-95', (SELECT id FROM public.categories WHERE name = 'Digestive & Gut Health' LIMIT 1)),
  ('Psyllium Husk Extract', 'psyllium-husk-extract', (SELECT id FROM public.categories WHERE name = 'Digestive & Gut Health' LIMIT 1)),
  ('Punarnava Extract', 'punarnava-extract', (SELECT id FROM public.categories WHERE name = 'Liver & Detox' LIMIT 1)),
  ('Safed Musli', 'safed-musli', (SELECT id FROM public.categories WHERE name = 'Men''s Health & Vitality' LIMIT 1)),
  ('Saffron Extract', 'saffron-extract', (SELECT id FROM public.categories WHERE name = 'Brain & Cognitive' LIMIT 1)),
  ('Senna Extract', 'senna-extract', (SELECT id FROM public.categories WHERE name = 'Digestive & Gut Health' LIMIT 1)),
  ('Shatavari', 'shatavari', (SELECT id FROM public.categories WHERE name = 'Women''s Health' LIMIT 1)),
  ('Shilajit', 'shilajit', (SELECT id FROM public.categories WHERE name = 'Men''s Health & Vitality' LIMIT 1)),
  ('Stevia Leaf Extract', 'stevia-leaf-extract', (SELECT id FROM public.categories WHERE name = 'Blood Sugar & Metabolic' LIMIT 1)),
  ('Tribulus Terrestris', 'tribulus-terrestris', (SELECT id FROM public.categories WHERE name = 'Men''s Health & Vitality' LIMIT 1)),
  ('Trikatu Blend', 'trikatu-blend', (SELECT id FROM public.categories WHERE name = 'Digestive & Gut Health' LIMIT 1)),
  ('Triphala', 'triphala', (SELECT id FROM public.categories WHERE name = 'Digestive & Gut Health' LIMIT 1)),
  ('Turmeric 95% Curcumin', 'turmeric-95-curcumin', (SELECT id FROM public.categories WHERE name = 'Anti-Inflammatory' LIMIT 1)),
  ('Vijaysar / Indian Kino Tree', 'vijaysar-indian-kino-tree', (SELECT id FROM public.categories WHERE name = 'Blood Sugar & Metabolic' LIMIT 1))
ON CONFLICT (slug) DO NOTHING;
